[package]
name = "stravant/draggerframework"
description = "Copy of DraggerFramework from Roblox Studio"
version = "0.1.4"
license = "None"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.4"
